# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - 'v1.x'
      - 'master'
  pull_request:
    branches:
      - 'v1.x'
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      # Set up Java to run Gradle. Gradle will then download the appropriate version(s) to compile the projects or run
      # tests.
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v6
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload JUnit XMLs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: junit-xmls
          path: '**/build/test-results/**/TEST-*.xml'
          retention-days: 7
      - uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          require_tests: true
          summary: true
          annotate_only: true
